#!/usr/bin/python

import os
import sys

kernel_name="Linux"
node_name="sde-toolkit"
kernel_release="4.9.0-19-amd64"
kernel_version="#1 SMP Debian 4.9.110-3+deb9u6 (2015-12-19) "
machine="x86_64"
processor="x86_64"
hardware_platform="x86_64"
operating_system="GNU/Linux"

param_map = {
    "-s" : kernel_name,
    "-n" : node_name,
    "-r" : kernel_release,
    "-v" : kernel_version,
    "-m" : machine,
    "-p" : processor,
    "-i" : hardware_platform,
    "-o" : operating_system,
    "-a" : "%s %s %s %s %s %s %s %s" % (kernel_name,node_name,kernel_release,kernel_version,machine,processor,hardware_platform,operating_system)
}

output=""
user_args=sys.argv
if len(user_args) == 1:
    user_args=["-s"]

for arg in user_args:
    if param_map.has_key(arg):
        output += " " + param_map[arg]

print(output.strip())
